using D3D12LookDevPTwithAI.Chat.Core;

namespace D3D12LookDevPTwithAI.ChatHost.Inference;

public static class ChatInferenceLimits
{
    public const int MaximumInputCharacters = 64 * 1024;
    public const int MaximumOutputCharacters =
        PipeProtocol.MaximumConversationMessageCharacters;
    public const int MaximumHistoryMessages = 512;
    public const int MaximumHistoryMessageCharacters =
        PipeProtocol.MaximumConversationMessageCharacters;
    public const int MaximumHistoryCharacters = 512 * 1024;
    public const int MaximumContextKeyCharacters = 256;
    public const int MaximumNameCharacters = 128;
    public const int MaximumRuntimeIdentifierCharacters = 64;
    public const int MaximumRuntimeStateCharacters = 32;
}

public enum ChatInferenceRole
{
    System,
    User,
    Assistant,
    Tool,
}

public sealed record ChatInferenceMessage(
    ChatInferenceRole Role,
    string Content,
    string? Name = null);

public sealed record ChatInferenceRequest(
    Guid ConversationId,
    string ContextKey,
    IReadOnlyList<ChatInferenceMessage> History,
    string UserText);

public sealed record ChatInferenceChunk(string Text);

public sealed record ChatInferenceRuntimeStatus(
    string RuntimeId,
    string DisplayName,
    bool IsReady,
    string State);

/// <summary>
/// Streams text generated by a local inference runtime. Normal completion of
/// the async sequence is the only success terminal. Cancellation must surface
/// as <see cref="OperationCanceledException"/>; safe runtime failures surface
/// as <see cref="ChatInferenceException"/>. Exception details are internal;
/// ChatCoordinator maps only explicitly supported codes to fixed public
/// messages. Protocol terminal events remain the responsibility of
/// ChatCoordinator.
/// </summary>
public interface IChatInferenceRuntime
{
    ValueTask<ChatInferenceRuntimeStatus> GetStatusAsync(
        CancellationToken cancellationToken = default);

    IAsyncEnumerable<ChatInferenceChunk> StreamAsync(
        ChatInferenceRequest request,
        CancellationToken cancellationToken = default);
}

public sealed class ChatInferenceException(
    string code,
    string message,
    bool retryable = false,
    Exception? innerException = null) : Exception(message, innerException)
{
    public string Code { get; } = code;
    public bool Retryable { get; } = retryable;
}
